"use client";
import { useState, useEffect, useRef } from "react";
import { useBookingsData } from "@/context/DataContext";
import { CommonForm } from "../common/CommonForm";
import { BookingDetails } from "./BookingDetails";
import { StaysList } from "./StaysList";
import { StayModal } from "../stay/StayModal";
import { searchDocuments } from "@/app/actions/crudActions";
import { toast } from "sonner";
import { BOOKING_STATUS_OPTIONS } from "./bookingConstants";
import { getStatusLabel } from "./bookingStatusUtils";
import { formatConfirmationNumber } from "../fields/AutoGeneratedField";

export function BookingForm() {
  const bookingsContext = useBookingsData();
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [selectedStay, setSelectedStay] = useState(null);
  const [isCopyMode, setIsCopyMode] = useState(false);
  const [stays, setStays] = useState([]);
  const [loadingStays, setLoadingStays] = useState(false);
  const loadingRef = useRef(false);

  const getDisplayName = (item) => {
    return item.confirmationNo
      ? formatConfirmationNumber(item.confirmationNo)
      : "New Booking";
  };



  useEffect(() => {
    if (bookingsContext.selectedItem) {
      setTimeout(() => {
        const topBarTitle = document.querySelector(".top-bar__title");
        if (topBarTitle) {
          topBarTitle.innerHTML = "";

          const confirmationSpan = document.createElement("span");
          const confirmationText = bookingsContext.selectedItem.confirmationNo
            ? formatConfirmationNumber(
                bookingsContext.selectedItem.confirmationNo
              )
            : "New Booking";
          confirmationSpan.textContent = confirmationText;
          topBarTitle.appendChild(confirmationSpan);

          if (bookingsContext.selectedItem.status) {
            const statusBadge = document.createElement("span");
            statusBadge.className = `status-badge status-${bookingsContext.selectedItem.status}`;
            statusBadge.textContent = getStatusLabel(
              bookingsContext.selectedItem.status,
              BOOKING_STATUS_OPTIONS
            );
            topBarTitle.appendChild(statusBadge);
          }
        }
      }, 100);
    }
  }, [
    bookingsContext.selectedItem,
    bookingsContext.selectedItem?.status,
    bookingsContext.selectedItem?.confirmationNo,
  ]);

  useEffect(() => {
    if (bookingsContext.selectedItem?._id) {
      setStays([]);
      loadRelatedStays(bookingsContext.selectedItem._id);
    } else if (bookingsContext.selectedItem?.staySummaries?.length > 0) {
      loadRelatedStaysFromSummaries(bookingsContext.selectedItem.staySummaries);
    } else {
      setStays([]);
    }
  }, [
    bookingsContext.selectedItem?._id,
    bookingsContext.selectedItem?.staySummaries,
  ]);

  const loadRelatedStaysFromSummaries = async (staySummaries) => {
    if (!staySummaries || staySummaries.length === 0 || loadingRef.current)
      return;

    try {
      loadingRef.current = true;
      setLoadingStays(true);

      const stayIdsToLoad = staySummaries.map((summary) => summary.stayId);
      const stayPromises = stayIdsToLoad.map((stayId) =>
        searchDocuments("stays", stayId, "_id")
      );

      const stayResults = await Promise.all(stayPromises);
      const loadedStays = stayResults.flat().filter(Boolean);

      setStays(loadedStays);
    } catch (err) {
      console.error("Error loading stays from summaries:", err);
      toast.error("Failed to load stays");
    } finally {
      loadingRef.current = false;
      setLoadingStays(false);
    }
  };

  const loadRelatedStays = async (bookingId) => {
    if (!bookingId || loadingRef.current) return;

    try {
      loadingRef.current = true;
      setLoadingStays(true);

      const booking = bookingsContext.selectedItem;
      const staySummaries = booking?.staySummaries || [];

      if (staySummaries.length === 0) {
        setStays([]);
        return;
      }

      const stayIdsToLoad = staySummaries.map((summary) => summary.stayId);
      const stayPromises = stayIdsToLoad.map((stayId) =>
        searchDocuments("stays", stayId, "_id")
      );

      const stayResults = await Promise.all(stayPromises);
      const loadedStays = stayResults.flat().filter(Boolean);

      setStays(loadedStays);
    } catch (err) {
      console.error("Error loading related stays:", err);
      toast.error("Failed to load stays");
    } finally {
      loadingRef.current = false;
      setLoadingStays(false);
    }
  };

  const handleAddStay = (e) => {
    if (e) {
      e.preventDefault();
      e.stopPropagation();
    }
    const newStay = {
      checkInDate: bookingsContext.selectedItem?.travelPeriodStart || "",
      checkOutDate: bookingsContext.selectedItem?.travelPeriodEnd || "",
      status: "unconfirmed",
      prepaid: "no",
    };

    setSelectedStay(newStay);
    setIsCopyMode(false);
    setIsModalOpen(true);
  };

  const handleEditStay = (stay) => {
    setSelectedStay(stay);
    setIsCopyMode(false);
    setIsModalOpen(true);
  };

  const handleCopyStay = (stay) => {
    const stayCopy = JSON.parse(JSON.stringify(stay));
    delete stayCopy._id;

    if (stayCopy.reference) {
      stayCopy.reference = `${stayCopy.reference} (Copy)`;
    } else {
      stayCopy.reference = `${stay.hotelName} (Copy)`;
    }

    stayCopy.hotelConfirmationNo = "";
    stayCopy.purchaseInvoice = "";
    stayCopy.commissionInvoice = "";
    stayCopy.status = "unconfirmed";

    setSelectedStay(stayCopy);
    setIsCopyMode(true);
    setIsModalOpen(true);
  };

  const handleViewStay = (stayId) => {
    const stayToView = stays.find((stay) => stay._id === stayId);
    if (stayToView) {
      setSelectedStay(stayToView);
      setIsCopyMode(false);
      setIsModalOpen(true);
    } else {
      const fetchStay = async () => {
        try {
          const result = await searchDocuments("stays", stayId, "_id");
          if (Array.isArray(result) && result.length > 0) {
            setSelectedStay(result[0]);
            setIsCopyMode(false);
            setIsModalOpen(true);
          } else {
            toast.error("Could not find stay details");
          }
        } catch (error) {
          console.error("Error fetching stay details:", error);
          toast.error("Error loading stay details");
        }
      };
      fetchStay();
    }
  };

  const handleRemoveStay = (stayIdToRemove) => {
    if (
      confirm(
        `Are you sure you want to remove this stay from the booking? This will not delete the stay itself.`
      )
    ) {
      const newStays = stays.filter((stay) => stay._id !== stayIdToRemove);
      const newSummaries = newStays.map((stay) => ({
        stayId: stay._id,
        hotelName: stay.hotelName || "Unknown Hotel",
        checkInDate: stay.checkInDate,
        checkOutDate: stay.checkOutDate,
      }));

      bookingsContext.updateField("staySummaries", newSummaries);
      setStays(newStays);

      const { stayIds, ...bookingData } = bookingsContext.selectedItem;
      const updatedBooking = {
        ...bookingData,
        staySummaries: newSummaries,
      };
      bookingsContext.updateItem(updatedBooking);

      toast.success("Stay removed and booking saved.");
    }
  };

  // Auto-save when stays are added or updated
  const autoSaveBookingAfterStayChange = async (newStaysList) => {
    if (!bookingsContext.selectedItem._id) return false;

    try {
      const newSummaries = newStaysList.map((stay) => ({
        stayId: stay._id,
        hotelName: stay.hotelName || "Unknown Hotel",
        checkInDate: stay.checkInDate,
        checkOutDate: stay.checkOutDate,
      }));

      bookingsContext.updateField("staySummaries", newSummaries);

      const { stayIds, ...bookingData } = bookingsContext.selectedItem;
      const updatedBooking = {
        ...bookingData,
        staySummaries: newSummaries,
      };

      const saveSuccess = await bookingsContext.updateItem(updatedBooking);
      return saveSuccess;
    } catch (error) {
      console.error("Error auto-saving booking:", error);
      return false;
    }
  };

  const handleStaySaved = async (savedStay) => {
    if (!savedStay || !savedStay._id) {
      return;
    }

    const existingStayIndex = stays.findIndex(
      (stay) => stay._id === savedStay._id
    );
    const newStaysList = [...stays];
    const isNewStay = existingStayIndex === -1;

    if (isNewStay) {
      newStaysList.push(savedStay);
      setStays(newStaysList);

      if (bookingsContext.selectedItem._id) {
        const saveSuccess = await autoSaveBookingAfterStayChange(newStaysList);

        if (saveSuccess) {
          toast.success("Stay added and booking auto-saved", {
            description: "The stay has been created and linked to this booking",
          });
        } else {
          toast.warning("Stay created but booking not auto-saved", {
            description: "Please save the booking manually to confirm changes",
          });
        }
      }
    } else {
      newStaysList[existingStayIndex] = savedStay;
      setStays(newStaysList);

      if (bookingsContext.selectedItem._id) {
        await autoSaveBookingAfterStayChange(newStaysList);
      }

      toast.success("Stay updated successfully");
    }

    setIsModalOpen(false);
  };

  return (
    <>
      {isModalOpen && (
        <StayModal
          stay={selectedStay}
          isCopyMode={isCopyMode}
          bookingId={bookingsContext.selectedItem?._id}
          onSave={handleStaySaved}
          onClose={() => setIsModalOpen(false)}
        />
      )}

      <CommonForm
        dataContext={bookingsContext}
        itemName="Booking"
        entityType="booking"
        basePath="bookings"
        displayName={getDisplayName}
      >
        <BookingDetails bookingsContext={bookingsContext} stays={stays} />
        <div className="col-full">
          <StaysList
            bookingsContext={bookingsContext}
            stays={stays}
            isLoading={loadingStays}
            onAddStay={handleAddStay}
            onEditStay={handleEditStay}
            onCopyStay={handleCopyStay}
            onViewStay={handleViewStay}
            onRemoveStay={handleRemoveStay}
          />
        </div>
      </CommonForm>

      <style jsx global>{`
        .top-bar__title {
          display: flex !important;
          align-items: center !important;
          gap: 12px !important;
          span {
            font-size: 1rem;
          }
        }

        .status-upcoming_no_action {
          background-color: #8b5cf6;
        }

        .status-upcoming_confirmation_sent {
          background-color: #3b82f6;
        }

        .status-stayed_missing_invoice {
          background-color: #f59e0b;
        }

        .status-invoicing_missing_both {
          background-color: #ef4444;
        }

        .status-invoicing_missing_sales {
          background-color: #f97316;
        }

        .status-invoicing_missing_commission {
          background-color: #f97316;
        }

        .status-completed {
          background-color: #10b981;
        }
      `}</style>
    </>
  );
}
