import type { Metadata } from "next";
import "../scss/main.scss";
import Header from "@/modules/header/Header";
import { Toaster } from "sonner";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <body className={`${inter.variable} antialiased`}>
        <Header />
        <main>{children}</main>
        <Toaster 
          position="bottom-right" 
          expand={false} 
          richColors 
          closeButton
        />
      </body>
    </html>
  );
}
